apiVersion: v1
data:
  server.properties: |
    #Minecraft server properties
    #Thu Sep 22 21:12:06 UTC 2022
    enable-jmx-monitoring=false
    rcon.port=25575
    level-seed=
    enable-command-block=true
    gamemode=adventure
    enable-query=false
    generator-settings={}
    level-name=world
    motd=A Minecraft Server
    query.port=25565
    pvp=true
    generate-structures=true
    difficulty=easy
    network-compression-threshold=256
    max-tick-time=60000
    require-resource-pack=true
    max-players=20
    use-native-transport=true
    online-mode=false
    enable-status=true
    allow-flight=false
    broadcast-rcon-to-ops=true
    view-distance=10
    resource-pack-prompt=
    server-ip=
    allow-nether=false
    server-port=25565
    enable-rcon=false
    sync-chunk-writes=true
    op-permission-level=4
    prevent-proxy-connections=false
    hide-online-players=false
    resource-pack=
    entity-broadcast-range-percentage=100
    simulation-distance=10
    rcon.password=
    player-idle-timeout=0
    force-gamemode=false
    debug=false
    rate-limit=0
    hardcore=false
    white-list=true
    broadcast-console-to-ops=false
    spawn-npcs=true
    spawn-animals=true
    snooper-enabled=true
    function-permission-level=2
    level-type=default
    text-filtering-config=
    spawn-monsters=true
    enforce-whitelist=false
    resource-pack-sha1=
    spawn-protection=16
    max-world-size=29999984
kind: ConfigMap
metadata:
  name: server-properties
  namespace: servers
