kind: Service
apiVersion: v1
metadata:
  name: paper-template
  namespace: servers
spec:
  ports:
    - name: minecraft
      protocol: TCP
      port: 25565
      targetPort: 25565
  selector:
    app: paper-template
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: paper-template
  namespace: servers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paper-template
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9225'
        prometheus.io/path: '/metrics'
      labels:
        app: paper-template
        net.chrotos.ingress.minecraft/discover: 'true'
        net.chrotos.ingress.minecraft/lobby: 'true'
        net.chrotos.chrotoscloud.gameserver/gamemode: 'lobby'
    spec:
      volumes:
        - name: workdir
          emptyDir: {}
        - name: paper-config
          configMap:
            name: paper-config
        - name: geoip-database
          emptyDir: {}
        - name: geoipupdate-secret
          secret:
            secretName: geoipupdate-secret
            optional: true
        - name: podinfo
          downwardAPI:
            items:
              - path: "labels"
                fieldRef:
                  fieldPath: metadata.labels
      initContainers:
        - name: paper-download
          image: katzen48/chrotoscloud-v2:paper-init-container
          volumeMounts:
            - name: workdir
              mountPath: /workdir
            - name: paper-config
              mountPath: /etc/config
            - name: podinfo
              mountPath: /etc/podinfo
            - name: geoip-database
              mountPath: /usr/local/share/GeoIP
            - name: geoipupdate-secret
              mountPath: /usr/local/etc/GeoIP.conf
              subPath: GeoIP.conf
          env:
            - name: DB_STRING
              valueFrom:
                secretKeyRef:
                  name: cloud-secret
                  key: DB_STRING
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: cloud-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloud-secret
                  key: DB_PASSWORD
            - name: VELOCITY_SECRET
              valueFrom:
                secretKeyRef:
                  name: velocity-secret
                  key: VELOCITY_SECRET
            - name: CONFIG_REPO_URL
              valueFrom:
                configMapKeyRef:
                  name: repositories-config
                  key: CONFIG_REPO_URL
            - name: CONFIG_REPO_USER
              valueFrom:
                secretKeyRef:
                  name: repositories-secret
                  key: CONFIG_REPO_USER
            - name: CONFIG_REPO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: repositories-secret
                  key: CONFIG_REPO_PASSWORD
            - name: WORLD_REPO_URL
              valueFrom:
                configMapKeyRef:
                  name: repositories-config
                  key: WORLD_REPO_URL
            - name: WORLD_REPO_USER
              valueFrom:
                secretKeyRef:
                  name: repositories-secret
                  key: WORLD_REPO_USER
            - name: WORLD_REPO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: repositories-secret
                  key: WORLD_REPO_PASSWORD
            - name: MAVEN_URL
              valueFrom:
                configMapKeyRef:
                  name: repositories-config
                  key: MAVEN_URL
            - name: MAVEN_USER
              valueFrom:
                secretKeyRef:
                  name: repositories-secret
                  key: MAVEN_USER
            - name: MAVEN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: repositories-secret
                  key: MAVEN_PASSWORD
          imagePullPolicy: IfNotPresent
      containers:
        - name: paper
          image: openjdk:17-jdk
          command:
            - java
          args:
            # Based on https://docs.papermc.io/paper/1.18/aikars-flags
            - '-Xms4G'
            - '-Xmx4G'
            - '-XX:+UseG1GC'
            - '-XX:+ParallelRefProcEnabled'
            - '-XX:MaxGCPauseMillis=200'
            - '-XX:+UnlockExperimentalVMOptions'
            - '-XX:+DisableExplicitGC'
            - '-XX:+AlwaysPreTouch'
            - '-XX:G1NewSizePercent=30'
            - '-XX:G1MaxNewSizePercent=40'
            - '-XX:G1HeapRegionSize=8M'
            - '-XX:G1ReservePercent=20'
            - '-XX:G1HeapWastePercent=5'
            - '-XX:G1MixedGCCountTarget=4'
            - '-XX:InitiatingHeapOccupancyPercent=15'
            - '-XX:G1MixedGCLiveThresholdPercent=90'
            - '-XX:G1RSetUpdatingPauseTimePercent=5'
            - '-XX:SurvivorRatio=32'
            - '-XX:+PerfDisableSharedMem'
            - '-XX:MaxTenuringThreshold=1'
            - '-Dusing.aikars.flags=https://mcflags.emc.gs'
            - '-Daikars.new.flags=true'
            - '-Dcom.mojang.eula.agree=true'
            - '-jar'
            - server.jar
            - '--nogui'
          workingDir: /opt/paper
          env:
            - name: DB_STRING
              valueFrom:
                secretKeyRef:
                  name: cloud-secret
                  key: DB_STRING
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: cloud-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloud-secret
                  key: DB_PASSWORD
            - name: CACHE_HOST
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: CACHE_HOST
            - name: CACHE_PORT
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: CACHE_PORT
            - name: CACHE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: CACHE_PASSWORD
            - name: QUEUE_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_USERNAME
            - name: QUEUE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_PASSWORD
            - name: QUEUE_HOST
              value: rabbitmq.core
            - name: QUEUE_PORT
              value: "5672"
          ports:
            - name: minecraft
              containerPort: 25565
              protocol: TCP
          resources:
            limits:
              memory: 5G
            requests:
              memory: 4G
          volumeMounts:
            - name: workdir
              mountPath: /opt/paper
            - name: podinfo
              mountPath: /etc/podinfo
            - name: geoip-database
              mountPath: /usr/local/share/GeoIP
          livenessProbe:
            tcpSocket:
              port: 25565
            initialDelaySeconds: 60
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 25565
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 2
            successThreshold: 1
            failureThreshold: 10
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
  serviceName: paper-template
