kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: chrotoscloud-worker
  namespace: core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chrotoscloud-worker
  template:
    metadata:
      labels:
        app: chrotoscloud-worker
    spec:
      volumes:
        - name: workdir
          emptyDir: {}
      initContainers:
        - name: worker-download
          image: katzen48/chrotoscloud-v2:worker-init-container
          volumeMounts:
            - name: workdir
              mountPath: /workdir
          imagePullPolicy: Always
      containers:
        - name: worker
          image: openjdk:17-jdk
          command:
            - java
          args:
            - '-Xms1G'
            - '-Xmx1G'
            - '-jar'
            - server.jar
          workingDir: /opt/worker
          env:
            - name: DB_STRING
              valueFrom:
                secretKeyRef:
                  name: cloud-secret
                  key: DB_STRING
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: cloud-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloud-secret
                  key: DB_PASSWORD
            - name: CACHE_HOST
              value: redis
            - name: CACHE_PORT
              value: '6379'
            - name: CACHE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: REDIS_PASSWORD
            - name: QUEUE_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_USERNAME
            - name: QUEUE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_PASSWORD
            - name: QUEUE_HOST
              value: rabbitmq.core
            - name: QUEUE_PORT
              value: '5672'
          resources:
            limits:
              memory: 2G
            requests:
              memory: 1G
          volumeMounts:
            - name: workdir
              mountPath: /opt/worker
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600