name: Java CI
on: 
  push:
    branches:
    - master
    paths:
    - mixins/**

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2
      - shell: bash
        env:
          GRADLE_PROPERTIES: ${{ secrets.GRADLE_PROPERTIES }}
        run: |
          mkdir -p ~/.gradle/
          echo "${GRADLE_PROPERTIES}" > gradle.properties
          echo "version = ${VERSION}" >> gradle.properties
      - uses: actions/setup-java@v1
        with:
          java-version: 17

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: artifactoryPublish
          gradle-version: 7.5.1
          build-root-directory: mixins

      - uses: actions/upload-artifact@v2
        with:
          name: mixins
          path: mixins/build/libs